async function loadBlob(blob, name = 'Photo', existingId = null, existingParams = null, existingMask = null, existingExtras = null) {
  if (state.objectURL) URL.revokeObjectURL(state.objectURL);
  state.objectURL = URL.createObjectURL(blob);
  state.originalBlob = blob;
  const img = new Image();
  img.decoding = 'async';
  img.src = state.objectURL;
  await img.decode();
  state.image = img;
  state.params = existingParams ? { ...deepCopy(DEFAULT_PARAMS), ...existingParams } : deepCopy(DEFAULT_PARAMS);
  state.maskStrokes = deepCopy(existingMask || []);
  state.healSpots = deepCopy(existingExtras?.healSpots || []);
  state.textLayers = deepCopy(existingExtras?.textLayers || []);
  state.projectVersions = deepCopy(existingExtras?.versions || []);
  await rehydrateLayers(existingExtras?.layers || []);
  state.undo = [];
  state.redo = [];
  invalidateGeometry(false);
  state.projectId = existingId || crypto.randomUUID();
  state.projectName = name.replace(/\.[^.]+$/, '') || 'LUMI Photo';
  $('#projectTitle').textContent = state.projectName;
  $('#imageMeta').textContent = `${img.naturalWidth} × ${img.naturalHeight} • LOCAL • NON-DESTRUCTIVE`;
  $('#exportInfo').textContent = `Original ${img.naturalWidth} × ${img.naturalHeight}`;
  if (!existingId) {
    const thumb = await makeThumbnail(blob);
    await putProject({ id: state.projectId, name: state.projectName, blob, params: state.params, maskStrokes: state.maskStrokes, healSpots:state.healSpots, textLayers:state.textLayers, layers:serializableLayers(), versions:state.projectVersions, thumb, createdAt: Date.now(), updatedAt: Date.now(), favorite:false });
  }
  syncUI(); updateHistoryButtons(); showPage('editor'); selectPanel(state.pendingPanel === 'editor' ? 'light' : state.pendingPanel); state.pendingPanel = 'light'; renderPreview(); renderLayerList(); updateHealUI(); await refreshProjects(); if (state.panel === 'auto') runAutoEnhance();
}

async function makeThumbnail(blob) {
  const url = URL.createObjectURL(blob);
  try { const img = new Image(); img.src = url; await img.decode(); const c = document.createElement('canvas'); const s = Math.min(1, 400 / Math.max(img.naturalWidth, img.naturalHeight)); c.width = Math.max(1, Math.round(img.naturalWidth * s)); c.height = Math.max(1, Math.round(img.naturalHeight * s)); c.getContext('2d').drawImage(img, 0, 0, c.width, c.height); return await new Promise(resolve => c.toBlob(resolve, 'image/jpeg', .72)); } finally { URL.revokeObjectURL(url); }
}

let saveTimer;
function scheduleProjectSave() { clearTimeout(saveTimer); if ($('#saveStatus')) $('#saveStatus').textContent = 'Saving…'; saveTimer = setTimeout(saveCurrentProject, 500); }
async function saveCurrentProject() { if (!state.projectId || !state.originalBlob || !state.db) return; const old = await getProject(state.projectId); await putProject({ id: state.projectId, name: state.projectName, blob: state.originalBlob, params: state.params, maskStrokes: state.maskStrokes, healSpots: state.healSpots, textLayers: state.textLayers, layers: serializableLayers(), versions: state.projectVersions, thumb: old?.thumb || await makeThumbnail(state.originalBlob), createdAt: old?.createdAt || Date.now(), updatedAt: Date.now(), favorite: old?.favorite || false }); if ($('#saveStatus')) $('#saveStatus').textContent = 'Saved locally'; refreshProjects(); }
function isEditedProject(p){const prm={...deepCopy(DEFAULT_PARAMS),...(p.params||{})};return Object.keys(DEFAULT_PARAMS).some(k=>typeof DEFAULT_PARAMS[k]==='number'&&Math.abs((prm[k]||0)-(DEFAULT_PARAMS[k]||0))>.0001)||!!p.maskStrokes?.length||!!p.healSpots?.length||!!p.textLayers?.length||!!p.layers?.length||p.params?.cropRatio!=='original'||p.params?.rotation||p.params?.flipH||p.params?.flipV;}
function projectCard(p, full = false) { const card = document.createElement(full ? 'article' : 'button'); card.className = full ? 'project-row' : 'project-card'; const url = URL.createObjectURL(p.thumb); const img = document.createElement('img'); img.alt = p.name; img.src = url; img.onload = () => setTimeout(() => URL.revokeObjectURL(url), 1000); if (!full) { card.appendChild(img); const label = document.createElement('span'); label.textContent = p.name; card.appendChild(label); card.onclick = () => loadBlob(p.blob, p.name, p.id, p.params, p.maskStrokes, {healSpots:p.healSpots,textLayers:p.textLayers,layers:p.layers,versions:p.versions}); return card; } const meta = document.createElement('div'); meta.className = 'project-row-meta'; const date = new Date(p.updatedAt).toLocaleString('th-TH', { dateStyle: 'medium', timeStyle: 'short' }); meta.innerHTML = `<strong>${p.favorite?'★ ':''}${escapeHtml(p.name)}</strong><span>${date}</span><small>${p.maskStrokes?.length || 0} mask stroke(s) · ${isEditedProject(p)?'Edited':'Original'}</small>`; const actions = document.createElement('div'); actions.className = 'project-row-actions'; const open = document.createElement('button'); open.textContent = 'Open'; open.onclick = () => loadBlob(p.blob, p.name, p.id, p.params, p.maskStrokes, {healSpots:p.healSpots,textLayers:p.textLayers,layers:p.layers,versions:p.versions}); const fav = document.createElement('button'); fav.textContent=p.favorite?'★':'☆'; fav.title='Favorite'; fav.onclick=async()=>{p.favorite=!p.favorite;p.updatedAt=Date.now();await putProject(p);refreshProjects();}; const dup = document.createElement('button'); dup.textContent='Copy'; dup.onclick=async()=>{const copy={...p,id:crypto.randomUUID(),name:`${p.name} Copy`,createdAt:Date.now(),updatedAt:Date.now(),favorite:false};await putProject(copy);refreshProjects();toast('Project duplicated');}; const rename = document.createElement('button'); rename.textContent='Rename'; rename.onclick=async()=>{const n=prompt('Project name',p.name);if(!n?.trim())return;p.name=n.trim();p.updatedAt=Date.now();await putProject(p);if(state.projectId===p.id){state.projectName=p.name;$('#projectTitle').textContent=p.name;}refreshProjects();}; const del = document.createElement('button'); del.textContent = 'Delete'; del.className = 'danger-text'; del.onclick = async () => { if (!confirm(`ลบโปรเจกต์ “${p.name}”?`)) return; await deleteProject(p.id); if (state.projectId === p.id) { state.projectId = null; state.image = null; state.originalBlob = null; $('#canvasEmpty').style.display = 'flex'; } await refreshProjects(); toast('Project deleted'); }; actions.append(open, fav, rename, dup, del); card.append(img, meta, actions); return card; }
async function refreshProjects() { if (!state.db) return; const allList = await listProjects(); const list = state.projectFilter === 'favorites' ? allList.filter(p => p.favorite) : allList; $('#projectCount').textContent = allList.length; $('#emptyProjects').style.display = allList.length ? 'none' : 'block'; $('#allProjectsEmpty').style.display = list.length ? 'none' : 'block'; if (state.projectFilter === 'favorites' && !list.length) $('#allProjectsEmpty').textContent = 'ยังไม่มี Favorite project'; else $('#allProjectsEmpty').textContent = 'ยังไม่มีโปรเจกต์'; const recent = $('#recentProjects'); recent.innerHTML = ''; allList.slice(0, 6).forEach(p => recent.appendChild(projectCard(p, false))); const all = $('#allProjects'); all.innerHTML = ''; list.forEach(p => all.appendChild(projectCard(p, true))); }
function escapeHtml(s) { return String(s).replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c])); }
function analyzeImage() { const c = document.createElement('canvas'); c.width = 96; c.height = 96; const ctx = c.getContext('2d', { willReadFrequently: true }); ctx.drawImage(state.image, 0, 0, 96, 96); const d = ctx.getImageData(0, 0, 96, 96).data; const luminance = []; const saturation = []; let sum = 0, sumR=0, sumG=0, sumB=0; for (let i = 0; i < d.length; i += 4) { const r = d[i] / 255, g = d[i+1] / 255, b = d[i+2] / 255; const l = .2126*r + .7152*g + .0722*b; const mx = Math.max(r,g,b), mn = Math.min(r,g,b); sum += l; sumR += r; sumG += g; sumB += b; luminance.push(l); saturation.push(mx === 0 ? 0 : (mx-mn)/mx); } luminance.sort((a,b) => a-b); const avg = sum / luminance.length; const p10 = luminance[Math.floor(luminance.length*.1)]; const p90 = luminance[Math.floor(luminance.length*.9)]; const range = p90 - p10; const avgSat = saturation.reduce((a,b) => a+b,0) / saturation.length; const ar=sumR/luminance.length, ag=sumG/luminance.length, ab=sumB/luminance.length; const warmth=clamp((ab-ar)*1.6,-.12,.12); const tintFix=clamp(((ar+ab)*.5-ag)*.8,-.08,.08); const suggested = { exposure: clamp((.50-avg)*1.05,-.45,.45), shadows: p10<.15 ? clamp((.16-p10)*1.8,0,.28) : 0, highlights: p90>.88 ? clamp(-((p90-.88)*1.8),-.28,0) : 0, contrast: range<.55 ? clamp((.55-range)*.42,0,.16) : 0, vibrance: avgSat<.34 ? clamp((.34-avgSat)*.65,0,.16) : 0, temperature: warmth, tint: tintFix }; return { avg,p10,p90,range,avgSat,warmth,tintFix,suggested }; }
function runAutoEnhance(strength = 1) { if (!state.image) return; const a = analyzeImage(); const before = snapshot(); const adjusted=Object.fromEntries(Object.entries(a.suggested).map(([k,v])=>[k,v*strength])); Object.assign(state.params, adjusted); commit(before); syncUI(); queueRender(); $('#analysisResult').innerHTML = `แสงเฉลี่ย <b>${Math.round(a.avg*100)}%</b> · Dynamic range <b>${Math.round(a.range*100)}%</b> · Saturation <b>${Math.round(a.avgSat*100)}%</b><br>WB ${a.warmth>0?'cool → warm':'warm → cool'}<br>Applied: Exposure ${adjusted.exposure.toFixed(2)}, Shadows ${pct(adjusted.shadows)}, Highlights ${pct(adjusted.highlights)}, Vibrance ${pct(adjusted.vibrance)}`; toast('Auto Enhance applied'); }
async function exportImage() { if (!state.image) return; loading(true, 'Rendering full quality…'); try { let source = makeGeometryCanvas(0); const requested = $('#exportResolution')?.value || 'original'; if (requested !== 'original' && Math.max(source.width, source.height) > Number(requested)) { const sc = Number(requested) / Math.max(source.width, source.height); const sized = document.createElement('canvas'); sized.width=Math.max(1,Math.round(source.width*sc)); sized.height=Math.max(1,Math.round(source.height*sc)); sized.getContext('2d').drawImage(source,0,0,sized.width,sized.height); source=sized; } const max = state.renderer.maxTextureSize; if (source.width > max || source.height > max) { const scale = max / Math.max(source.width, source.height); const tmp = document.createElement('canvas'); tmp.width = Math.round(source.width * scale); tmp.height = Math.round(source.height * scale); tmp.getContext('2d').drawImage(source, 0, 0, tmp.width, tmp.height); source = tmp; toast(`ลดขนาดตาม WebGL limit ${max}px`); } const mask = makeMaskCanvas(source.width, source.height); const out = document.createElement('canvas'); const renderer = new WebGLRenderer(out); renderer.render(source, state.params, mask); const type = $('#exportType').value; const quality = Number($('#exportQuality').value) / 100; const blob = await new Promise((resolve, reject) => out.toBlob(b => b ? resolve(b) : reject(new Error('Encode failed')), type, quality)); const ext = { 'image/jpeg':'jpg', 'image/png':'png', 'image/webp':'webp' }[type] || 'jpg'; const file = new File([blob], `${state.projectName || 'LUMI'}-edited.${ext}`, { type }); if (navigator.canShare && navigator.canShare({ files:[file] })) await navigator.share({ files:[file], title:'LUMI AI Export' }); else { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = file.name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 2000); } modal('exportModal', false); toast('Export complete'); } catch (err) { if (err?.name !== 'AbortError') { console.error(err); toast('Export ไม่สำเร็จ'); } } finally { loading(false); } }
function resetCanvasGesture() { Object.assign(state.gesture, { scale:1, x:0, y:0, pointers:new Map(), startDist:0, startScale:1 }); applyCanvasTransform(); }
function applyCanvasTransform() { const { scale,x,y } = state.gesture; $('#canvasStack').style.transform = `translate(${x}px,${y}px) scale(${scale})`; }
function setupCanvasGestures() { const stage = $('#canvasStack'); let lastTap = 0; stage.addEventListener('pointerdown', e => { if (state.panel === 'mask') return; stage.setPointerCapture(e.pointerId); state.gesture.pointers.set(e.pointerId, { x:e.clientX, y:e.clientY }); if (state.gesture.pointers.size === 2) { const p = [...state.gesture.pointers.values()]; state.gesture.startDist = Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y); state.gesture.startScale = state.gesture.scale; } const now = Date.now(); if (now-lastTap < 300) { resetCanvasGesture(); lastTap = 0; } else lastTap = now; }); stage.addEventListener('pointermove', e => { if (state.panel === 'mask' || !state.gesture.pointers.has(e.pointerId)) return; const old = state.gesture.pointers.get(e.pointerId); state.gesture.pointers.set(e.pointerId, { x:e.clientX, y:e.clientY }); if (state.gesture.pointers.size === 1 && state.gesture.scale > 1) { state.gesture.x += e.clientX-old.x; state.gesture.y += e.clientY-old.y; } else if (state.gesture.pointers.size === 2) { const p = [...state.gesture.pointers.values()]; const dist = Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y); state.gesture.scale = clamp(state.gesture.startScale*(dist/state.gesture.startDist),1,5); if (state.gesture.scale === 1) { state.gesture.x=0; state.gesture.y=0; } } applyCanvasTransform(); }); const end = e => state.gesture.pointers.delete(e.pointerId); stage.addEventListener('pointerup', end); stage.addEventListener('pointercancel', end); }
function pointFromMaskEvent(e) { const rect = $('#maskOverlay').getBoundingClientRect(); return { x: clamp((e.clientX-rect.left)/rect.width, 0, 1), y: clamp((e.clientY-rect.top)/rect.height, 0, 1) }; }
function setupMaskDrawing() { const overlay = $('#maskOverlay'); overlay.addEventListener('pointerdown', e => { if (state.panel !== 'mask' || !state.image) return; e.preventDefault(); overlay.setPointerCapture(e.pointerId); const before = snapshot(); const stroke = { erase: state.maskMode === 'erase', size: state.maskBrush, points: [pointFromMaskEvent(e)] }; state.maskStrokes.push(stroke); state.maskDrawing = { pointerId:e.pointerId, stroke, before }; drawMaskOverlay(); }); overlay.addEventListener('pointermove', e => { if (!state.maskDrawing || state.maskDrawing.pointerId !== e.pointerId) return; state.maskDrawing.stroke.points.push(pointFromMaskEvent(e)); drawMaskOverlay(); }); const finish = e => { if (!state.maskDrawing || state.maskDrawing.pointerId !== e.pointerId) return; commit(state.maskDrawing.before); state.maskDrawing = null; queueRender(); }; overlay.addEventListener('pointerup', finish); overlay.addEventListener('pointercancel', finish); }
async function refreshStatus() { $('#modeValue').textContent = window.matchMedia('(display-mode: standalone)').matches || navigator.standalone ? 'Installed PWA' : 'Browser'; $('#offlineValue').textContent = !('serviceWorker' in navigator) ? 'Unavailable' : navigator.serviceWorker.controller ? 'Active' : 'Ready after refresh'; if (state.renderer) $('#rendererValue').textContent = `WebGL2 Pro · max ${state.renderer.maxTextureSize}px`; if (state.db) $('#projectCount').textContent = (await listProjects()).length; }
function openFeatureModal(feature, ai = false) { const data = ai ? AI_FEATURES[feature] : INFO_FEATURES[feature]; if (!data) return; $('#featureStatus').textContent = data.status; $('#featureTitle').textContent = data.title; $('#featureBody').innerHTML = `<p>${escapeHtml(data.body)}</p>${data.bullets?.length ? `<ul>${data.bullets.map(x => `<li>${escapeHtml(x)}</li>`).join('')}</ul>` : ''}${ai ? '<div class="feature-warning">Cloud AI ยังไม่ส่งรูปหรือเรียก API ใด ๆ ในเวอร์ชันนี้</div>' : ''}`; if (ai && data.fallbackPanel) { const localLabel = data.fallbackPanel === 'mask' ? 'Manual Mask' : data.fallbackPanel === 'beauty' ? 'Local Beauty' : data.fallbackPanel === 'crop' ? 'Crop / Canvas' : data.fallbackPanel; $('#featureActionBtn').textContent = state.image ? `Open ${localLabel}` : 'Choose Photo for Local Tool'; $('#featureActionBtn').onclick = () => { modal('featureModal', false); if (state.image) { showPage('editor'); selectPanel(data.fallbackPanel); } else { state.pendingPanel = data.fallbackPanel; $('#photoInput').click(); } }; } else { $('#featureActionBtn').textContent = 'Close'; $('#featureActionBtn').onclick = () => modal('featureModal', false); } modal('featureModal', true); }
async function clearOfflineCache() { if (!('caches' in window)) { toast('Cache API unavailable'); return; } const keys = await caches.keys(); await Promise.all(keys.map(k => caches.delete(k))); toast('Offline cache cleared'); setTimeout(() => location.reload(), 450); }
