function openAdvancedTool(kind,t=null){
  $('#advancedToolStatus').textContent='LUMI v3';$('#advancedToolControls').innerHTML='';$('#advancedToolActions').innerHTML='';$('#advancedToolApplyBtn').textContent='Apply';let apply=()=>modal('advancedToolModal',false);
  if(kind==='batch'){ $('#advancedToolTitle').textContent='Batch Editor';$('#advancedToolDesc').textContent='Select multiple photos. LUMI applies the current non-destructive look and exports each image as JPEG.';$('#advancedToolControls').innerHTML='<div class="analysis-card">Uses your current Light / Color / HSL / Curve / Beauty / Film settings. Browser download policies may ask permission for multiple files.</div>';$('#advancedToolApplyBtn').textContent='Select Photos';apply=()=>{state.batchMode='batch';$('#batchInput').click();}; }
  else if(kind==='collage'){ $('#advancedToolTitle').textContent='Collage Studio';$('#advancedToolDesc').textContent='Create a clean square grid collage locally from multiple photos.';$('#advancedToolControls').innerHTML='<div class="analysis-card">Choose 2–9 images. LUMI builds a local grid canvas and opens it as a new editable project.</div>';$('#advancedToolApplyBtn').textContent='Choose Photos';apply=()=>{state.batchMode='collage';$('#batchInput').click();}; }
  else if(kind==='camera'){ $('#advancedToolTitle').textContent='Camera Capture';$('#advancedToolDesc').textContent='Capture a photo from the browser camera and send it directly to the editor.';$('#advancedToolControls').innerHTML='<video id="cameraPreview" playsinline autoplay muted style="width:100%;max-height:48dvh;object-fit:cover;border-radius:16px;background:#050811"></video>';$('#advancedToolApplyBtn').textContent='Start Camera';apply=startCameraCapture; }
  else if(kind==='creator'){ $('#advancedToolTitle').textContent='Creator Studio';$('#advancedToolDesc').textContent='Add a text / watermark layer to the current project.';$('#advancedToolControls').innerHTML='<label style="display:block;border:0;padding:0">Text<input id="creatorText" value="LUMI" style="width:100%;margin-top:7px;background:#11182a;border:1px solid var(--line);color:#fff;border-radius:12px;padding:10px"></label>'+sliderMarkup('size','Text Size',16,140,1,48,v=>`${v}px`);apply=()=>{if(!state.image)return toast('Choose a photo first');const text=$('#creatorText').value||'LUMI',size=Number($('[data-adv-param="size"]').value);state.textLayers.push({id:crypto.randomUUID(),text,size,x:.5,y:.88,opacity:.9,color:'#ffffff'});invalidateGeometry(false);queueRender();scheduleProjectSave();modal('advancedToolModal',false);toast('Text layer added');renderLayerList();}; }
  else if(kind==='matchlook'){ $('#advancedToolTitle').textContent='Match Look';$('#advancedToolDesc').textContent='Reference matching UI is ready. Select a reference image to derive average tone and color locally.';$('#advancedToolControls').innerHTML='<input id="referenceInput" type="file" accept="image/*"><div id="matchLookStatus" class="analysis-card" style="margin-top:10px">Choose a reference photo.</div>';apply=applyMatchLook; }
  else if(kind==='asklumi'){ $('#advancedToolTitle').textContent='Ask LUMI 2.0';$('#advancedToolDesc').textContent='Thai / English natural-language edit planning. Local commands are converted to structured parameters; generative commands are routed to the matching AI model.';$('#advancedToolControls').innerHTML='<textarea id="askLumiText" rows="4" placeholder="เช่น หน้าสว่างขึ้น แต่เก็บท้องฟ้าไว้" style="width:100%;background:#11182a;border:1px solid var(--line);color:#fff;border-radius:14px;padding:11px"></textarea><div id="askLumiPlan" class="analysis-card" style="margin-top:10px">Plan will appear here.</div>';$('#advancedToolApplyBtn').textContent='Create Plan';apply=askLumiPlan; }
  else if(kind==='aistatus'){ $('#advancedToolTitle').textContent='AI Edit Status';$('#advancedToolDesc').textContent='Dependency view for masks and cloud AI edits.';$('#advancedToolControls').innerHTML=aiDependencyMarkup();$('#advancedToolApplyBtn').textContent='Update Status';apply=()=>{refreshAIStatus();$('#advancedToolControls').innerHTML=aiDependencyMarkup();}; }
  else if(kind==='storage'){ $('#advancedToolTitle').textContent='Storage Manager';$('#advancedToolDesc').textContent='Inspect local project/cache usage without touching originals.';$('#advancedToolControls').innerHTML='<div id="storageStats" class="analysis-card">Calculating…</div>';storageStats().then(x=>$('#storageStats').innerHTML=x);$('#advancedToolApplyBtn').textContent='Clear Cache Only';apply=clearOfflineCache; }
  else if(kind==='privacy'){ $('#advancedToolTitle').textContent='Privacy Center';$('#advancedToolDesc').textContent='Clear separation between local and cloud processing.';$('#advancedToolControls').innerHTML='<div class="analysis-card"><b>LOCAL</b><br>Light · Color · HSL · Curve · Levels · Grading · Beauty Basic · Mask · Crop · Layers · Retouch · Film · Projects · Export<br><br><b>CLOUD / ENDPOINT</b><br>rembg · Real-ESRGAN · SAM 2 · FLUX.1 Schnell · Stable Diffusion XL<br><br>No photo is uploaded until you explicitly consent inside an AI tool.</div>';$('#advancedToolApplyBtn').textContent='Done'; }
  else if(kind==='metadata'){ $('#advancedToolTitle').textContent='Pro Info Panel';$('#advancedToolDesc').textContent='Image information available to this PWA.';$('#advancedToolControls').innerHTML=metadataMarkup();$('#advancedToolApplyBtn').textContent='Done'; }
  else if(kind==='history'){ $('#advancedToolTitle').textContent='Edit History Pro';$('#advancedToolDesc').textContent='Current undo / redo state.';$('#advancedToolControls').innerHTML=`<div class="analysis-card">Undo states: ${state.undo.length}<br>Redo states: ${state.redo.length}<br>Mask strokes: ${state.maskStrokes.length}<br>Retouch spots: ${state.healSpots.length}</div>`;$('#advancedToolApplyBtn').textContent='Close'; }
  else if(kind==='versions'){ $('#advancedToolTitle').textContent='Project Versions';$('#advancedToolDesc').textContent='Save a named non-destructive snapshot in this browser session.';$('#advancedToolControls').innerHTML='<input id="versionName" value="Version '+(state.projectVersions.length+1)+'" style="width:100%;background:#11182a;border:1px solid var(--line);color:#fff;border-radius:12px;padding:10px"><div id="versionList" class="project-list" style="margin-top:10px"></div>';renderVersionList();apply=saveVersion; }
  else if(kind==='socialexport'){ $('#advancedToolTitle').textContent='Social Export';$('#advancedToolDesc').textContent='Choose a platform ratio and jump to Crop / Export.';$('#advancedToolActions').innerHTML=['Instagram 4:5','Story 9:16','Square 1:1','YouTube 16:9'].map(x=>`<button data-social="${x}">${x}</button>`).join('');$$('[data-social]').forEach(b=>b.onclick=()=>{const r=b.dataset.social.includes('9:16')?'9:16':b.dataset.social.includes('1:1')?'1:1':b.dataset.social.includes('16:9')?'16:9':'4:5';const before=snapshot();state.params.cropRatio=r;invalidateGeometry(true);commit(before);modal('advancedToolModal',false);openTool('crop');});$('#advancedToolApplyBtn').textContent='Done'; }
  else if(kind==='gradientmask'||kind==='rangemask'||kind==='controlpoint'){ $('#advancedToolTitle').textContent=t?.title||'Selective Tool';$('#advancedToolDesc').textContent=t?.desc||'Selective adjustment';$('#advancedToolControls').innerHTML='<div class="analysis-card">This selective mode shares the same mask adjustment engine. Use the manual brush now; gradient/range geometry is represented as the next local mask primitive.</div>';$('#advancedToolApplyBtn').textContent='Open Mask';apply=()=>{modal('advancedToolModal',false);openTool('mask');}; }
  else {showAdvancedInfo(t||{title:kind,status:'FEATURE',desc:'Feature'});return;}
  $('#advancedToolApplyBtn').onclick=apply;modal('advancedToolModal',true);
}

function metadataMarkup(){if(!state.image)return'<div class="analysis-card">Choose a photo to inspect it.</div>';return `<div class="analysis-card"><b>${escapeHtml(state.projectName||'Photo')}</b><br>${state.image.naturalWidth} × ${state.image.naturalHeight}<br>${((state.image.naturalWidth*state.image.naturalHeight)/1e6).toFixed(1)} MP<br>Type: ${state.originalBlob?.type||'unknown'}<br>File size: ${state.originalBlob?`${(state.originalBlob.size/1024/1024).toFixed(2)} MB`:'unknown'}<br>Renderer: WebGL2 · local</div>`;}
function aiDependencyMarkup(){return `<div class="analysis-card">✓ Global Light / Color — Current<br>${state.maskStrokes.length?'✓':'○'} Manual Mask — ${state.maskStrokes.length?'Current':'None'}<br>${state.params.cropRatio!=='original'||state.params.rotation?'!':'✓'} Geometry — ${state.params.cropRatio}${state.params.rotation?` · ${state.params.rotation}°`:''}<br>${state.aiResult?'✓ Cloud AI result exists':'○ No cloud AI result'}<br><br>Geometry changes invalidate semantic AI masks by design; LUMI will request refresh after SAM 2 is connected.</div>`;}
async function storageStats(){let projects=[];try{projects=await listProjects();}catch(e){}const bytes=projects.reduce((n,p)=>n+(p.blob?.size||0)+(p.thumb?.size||0),0);let cacheNames=[];try{cacheNames=await caches.keys();}catch(e){}return `<b>Projects</b> ${projects.length}<br><b>Project assets</b> ~${(bytes/1024/1024).toFixed(1)} MB<br><b>Offline caches</b> ${cacheNames.length}<br><b>Current original</b> ${state.originalBlob?`${(state.originalBlob.size/1024/1024).toFixed(1)} MB`:'none'}`;}

async function applyMatchLook(){const f=$('#referenceInput')?.files?.[0];if(!f||!state.image)return toast('Choose current photo and reference');const url=URL.createObjectURL(f);try{const im=new Image();im.src=url;await im.decode();const c=document.createElement('canvas');c.width=64;c.height=64;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0,64,64);const d=ctx.getImageData(0,0,64,64).data;let r=0,g=0,b=0;for(let i=0;i<d.length;i+=4){r+=d[i];g+=d[i+1];b+=d[i+2];}const n=d.length/4;r/=n;g/=n;b/=n;const warmth=clamp((r-b)/255,-1,1),tint=clamp((g-(r+b)/2)/255,-1,1);const before=snapshot();state.params.temperature=warmth*.35;state.params.tint=tint*.25;state.params.vibrance=.08;commit(before);syncUI();queueRender();$('#matchLookStatus').textContent=`Matched average color · Temp ${pct(state.params.temperature)} · Tint ${pct(state.params.tint)}`;toast('Reference color matched');}finally{URL.revokeObjectURL(url);}}

function askLumiPlan(){const txt=($('#askLumiText')?.value||'').trim();if(!txt)return;const lower=txt.toLowerCase();const plan={local:{},ai:null};if(/สว่าง|bright|exposure/.test(lower))plan.local.exposure=.25;if(/ผิว|skin/.test(lower)){plan.local.skinGlow=.08;plan.local.skinSmooth=.12;}if(/ท้องฟ้า|sky/.test(lower))plan.ai='sky-mask';if(/ลบคน|remove|ลบวัตถุ/.test(lower))plan.ai='ai-remove';if(/เสื้อ|outfit/.test(lower))plan.ai='ai-outfit';if(/9:16|expand|ขยาย/.test(lower))plan.ai='generative-expand';if(/ฟิล์ม|film/.test(lower)){plan.local.filmFade=.16;plan.local.grain=.10;plan.local.halation=.08;}if(/ลดเขียว|green/.test(lower))plan.local.hsl_green_s=-.22;$('#askLumiPlan').innerHTML=`<b>Structured Edit Plan</b><pre style="white-space:pre-wrap;font-size:9px">${escapeHtml(JSON.stringify(plan,null,2))}</pre>`;$('#advancedToolApplyBtn').textContent='Apply Plan';$('#advancedToolApplyBtn').onclick=()=>{if(!state.image)return toast('Choose a photo first');const before=snapshot();Object.assign(state.params,plan.local);commit(before);syncUI();queueRender();modal('advancedToolModal',false);if(plan.ai)openAIRun(plan.ai);else openTool('light');};}

function renderVersionList(){const root=$('#versionList');if(!root)return;root.innerHTML=state.projectVersions.map((v,i)=>`<button class="secondary-btn" data-version="${i}" style="width:100%;margin-top:6px">${escapeHtml(v.name)}</button>`).join('');$$('[data-version]',root).forEach(b=>b.onclick=()=>{const v=state.projectVersions[Number(b.dataset.version)];restoreSnapshot(v.snapshot);modal('advancedToolModal',false);toast(`Restored ${v.name}`);});}
function saveVersion(){if(!state.image)return toast('Choose a photo first');const name=$('#versionName').value.trim()||`Version ${state.projectVersions.length+1}`;state.projectVersions.push({name,snapshot:snapshot(),date:Date.now()});renderVersionList();toast('Version saved');}

async function startCameraCapture(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera API unavailable');if(!state.cameraStream){state.cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});$('#cameraPreview').srcObject=state.cameraStream;$('#advancedToolApplyBtn').textContent='Capture Photo';return;}const v=$('#cameraPreview'),c=document.createElement('canvas');c.width=v.videoWidth||1280;c.height=v.videoHeight||720;c.getContext('2d').drawImage(v,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.94));state.cameraStream.getTracks().forEach(t=>t.stop());state.cameraStream=null;modal('advancedToolModal',false);await loadBlob(blob,`Camera ${new Date().toLocaleTimeString()}.jpg`);}catch(e){toast(e.message);}}

async function handleBatchFiles(files){const list=[...files];if(!list.length)return;if(state.batchMode==='collage'){state.batchMode=null;return createCollage(list);}state.batchMode=null;if(!state.image)return toast('Open one edited photo first so Batch can reuse its look');loading(true,`Batch 0/${list.length}`);try{let done=0;for(const f of list){const url=URL.createObjectURL(f);try{const im=new Image();im.src=url;await im.decode();const max=2048,sc=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight)),src=document.createElement('canvas');src.width=Math.round(im.naturalWidth*sc);src.height=Math.round(im.naturalHeight*sc);src.getContext('2d').drawImage(im,0,0,src.width,src.height);const out=document.createElement('canvas'),r=new WebGLRenderer(out);r.render(src,state.params,null);const blob=await new Promise(res=>out.toBlob(res,'image/jpeg',.9));const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`LUMI-${f.name.replace(/\.[^.]+$/,'')}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),4000);done++;loading(true,`Batch ${done}/${list.length}`);}finally{URL.revokeObjectURL(url);}}toast(`Batch exported ${done} photo(s)`);}finally{loading(false);}}

async function createCollage(files){loading(true,'Building collage…');try{const imgs=[];for(const f of files.slice(0,9)){const u=URL.createObjectURL(f),im=new Image();im.src=u;await im.decode();imgs.push([im,u]);}const n=imgs.length,cols=Math.ceil(Math.sqrt(n)),rows=Math.ceil(n/cols),cell=700,c=document.createElement('canvas');c.width=cols*cell;c.height=rows*cell;const ctx=c.getContext('2d');ctx.fillStyle='#0B1020';ctx.fillRect(0,0,c.width,c.height);imgs.forEach(([im],i)=>{const x=(i%cols)*cell,y=Math.floor(i/cols)*cell,ir=im.naturalWidth/im.naturalHeight;let sw=im.naturalWidth,sh=im.naturalHeight;if(ir>1){sw=im.naturalHeight;}else{sh=im.naturalWidth;}const sx=(im.naturalWidth-sw)/2,sy=(im.naturalHeight-sh)/2;ctx.drawImage(im,sx,sy,sw,sh,x+4,y+4,cell-8,cell-8);});const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.94));imgs.forEach(x=>URL.revokeObjectURL(x[1]));modal('advancedToolModal',false);await loadBlob(blob,'LUMI Collage.jpg');}finally{loading(false);}}

function applyHealSpots(canvas){if(!state.healSpots?.length)return;const ctx=canvas.getContext('2d');for(const sp of state.healSpots){const x=sp.x*canvas.width,y=sp.y*canvas.height,r=Math.max(4,sp.r*Math.min(canvas.width,canvas.height));const sx=clamp(x-r*1.7,r,canvas.width-r),sy=clamp(y-r*.35,r,canvas.height-r);const patch=document.createElement('canvas');patch.width=Math.ceil(r*2);patch.height=Math.ceil(r*2);const pctx=patch.getContext('2d');pctx.drawImage(canvas,sx-r,sy-r,r*2,r*2,0,0,patch.width,patch.height);ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();ctx.globalAlpha=.88;ctx.filter=`blur(${Math.max(.5,r*.08)}px)`;ctx.drawImage(patch,x-r,y-r,r*2,r*2);ctx.restore();}}
function applyTextLayers(canvas){if(!state.textLayers?.length)return;const ctx=canvas.getContext('2d');state.textLayers.forEach(t=>{ctx.save();ctx.globalAlpha=t.opacity??.9;ctx.fillStyle=t.color||'#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`700 ${Math.max(12,(t.size||48)/1000*Math.min(canvas.width,canvas.height))}px -apple-system,BlinkMacSystemFont,sans-serif`;ctx.shadowColor='rgba(0,0,0,.4)';ctx.shadowBlur=8;ctx.fillText(t.text,t.x*canvas.width,t.y*canvas.height);ctx.restore();});}
function applyImageLayers(canvas){if(!state.layers?.length)return;const ctx=canvas.getContext('2d');for(const l of state.layers){if(!l.image)continue;const sc=(l.scale||.5)*Math.min(canvas.width,canvas.height)/Math.max(l.image.naturalWidth,l.image.naturalHeight),w=l.image.naturalWidth*sc,h=l.image.naturalHeight*sc,x=(l.x??.5)*canvas.width-w/2,y=(l.y??.5)*canvas.height-h/2;ctx.save();ctx.globalAlpha=l.opacity??1;ctx.globalCompositeOperation=l.blend||'source-over';ctx.drawImage(l.image,x,y,w,h);ctx.restore();}}
